#!/usr/bin/env bash
# installs an nginx web server that returns a customized HTTP GET response
#
# Requirements:
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# You can’t use systemctl for restarting nginx
# When querying Nginx at its root / with a GET request (requesting a page)
#+ using curl, it must return a page that contains the string Hello World!
# As an answer file, write a Bash script that configures a new Ubuntu machine
#+ to respect above requirements (this script will be run on the server itself)

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /usr/share/nginx/html/index.html
sudo service nginx start
