#!/usr/bin/env bash
# installs an nginx web server that returns a customized HTTP GET response
#
# Requirements:
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# You can’t use systemctl for restarting nginx
# When querying Nginx at its root / with a GET request (requesting a page)
#+ using curl, it must return a page that contains the string Hello World!
# As an answer file, write a Bash script that configures a new Ubuntu machine
#+ to respect above requirements (this script will be run on the server itself)

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > var/www/html/index.html
service nginx start
