#!/usr/bin/env bash
# installs an nginx web server that returns a customized HTTP GET response
# redirects "server/redirect_me" to another page

replacement_string="server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/google.com;\n\t}\n"

sudo apt-get update
sudo apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html
sudo sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-available/default
sudo service nginx start
