#!/usr/bin/env bash
# Install and configure HAproxy on load balancing server
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

config_settings=\
"
frontend www
        bind *:80
        mode http
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 58381-web-01 54.152.106.255:80 check
        server 58381-web-02 100.25.181.181:80 check
"

# prepare environment and start installation
sudo apt-get -y update
sudo apt-get -y install haproxy

# backup original configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# edit configuration file settings
echo "$config_settings" | sudo tee -a /etc/haproxy/haproxy.cfg

# manage HAProxy via init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# start load balancer process
sudo service haproxy restart
