#!/usr/bin/env bash
# creates a file containing its PID;
#+ displays "To infinity and beyond" indefinitely
#+ displays "I hate the kill command" when receiving a SIGTERM signal
#+ displays "Y U no love me?!" when receiving a SIGINT signal
#+ deletes pid file and terminates itself when receiving a SIGQUIT or SIGTERM signal

echo $$ > /var/run/myscript.pid

while ((1))
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'rm /var/run/myscript.pid; echo "I hate the kill command"; kill $$' SIGQUIT SIGTERM
done
