#!/usr/bin/env bash
# creates a file containing its PID;
#+ displays "To infinity and beyond" indefinitely
#+ displays "I hate the kill command" when receiving a SIGTERM signal
#+ displays "Y U no love me?!" when receiving a SIGINT signal
#+ deletes pid file and terminates itself when receiving a SIGQUIT or SIGTERM signal
echo $$ > /var/run/myscript.pid

trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command; rm -f /var/run/myscript.pid'" SIGQUIT
trap "echo 'I hate the kill command; rm -f /var/run/myscript.pid'" SIGTERM

while ((1))
do
    echo "To infinity and beyond"
    sleep 2
done
