#!/usr/bin/env bash
# displays numbers from 1 to 100 in a list format with these requirements:
#+ Displays FizzBuzz when the number is a multiple of 3 and 5
#+ Displays Fizz when the number is multiple of 3
#+ Displays Buzz when the number is a multiple of 5
#+ Otherwise, displays the number

i=1

until [ "$i" -ge 101 ]
do
    if [[ "$i % 15" -eq 0 ]]
    then
        echo "FizzBuzz"
    elif [[ "$i % 3" -eq 0 ]]
    then
	echo "Fizz"
    elif [[ "$i % 5" -eq 0 ]]
    then
	echo "Buzz"
    else
        echo "$i"
    fi
    ((i++))
done
