#!/usr/bin/env bash
# this script displays the content of the file /etc/passwd
#+ only displays the username, user id, and home directory path fields

while read -r line
do
    echo "${line}"
done < /etc/passwd | cut --field=1,3,6 -d ":"
