#!/usr/bin/env bash
# displays the content of the current directory in a list format
#+ where only the part of the name after the first dash is displayed
list=$(ls ./)
for i in $list
do
    newname="$(ls "$i" | cut -f 2- -d "-")"
    echo "$newname"
done
