#!/usr/bin/env bash
# configures an Ubuntu server with the below requirements:
#+ localhost resolves to 127.0.0.2
#+ facebook.com resolves to 8.8.8.8.

# Backup the existing hosts file
sudo cp /etc/hosts hosts.bak

# Update the hosts file to include the custom hostname resolution
sed -i s/127.*$/127.0.0.2\\tlocalhost\\n8.8.8.8\\tfacebook.com/g hosts.bak

# Copy the contents of new file to hosts file
cp -f hosts.bak /etc/hosts
