#!/usr/bin/env bash
# configures an Ubuntu server with the below requirements:
#+ localhost resolves to 127.0.0.2
#+ facebook.com resolves to 8.8.8.8.

# Backup the existing hosts file
sudo cp /etc/hosts hosts.bak

# Update the hosts file to include the custom hostname resolution
# sed -i s/127.*$/127.0.0.2\\tlocalhost\\n8.8.8.8\\tfacebook.com/g hosts.bak
echo "127.0.0.2 localhost" | sudo tee /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

# Copy the contents of new file to hosts file
cp -f hosts.bak /etc/hosts
