#!/usr/bin/env bash
# Shortens the fix in the task1 script
sed -i "1i user nginx;" /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
pkill apache2
sudo -u nginx service nginx restart
